biolib_version: 2
modules:
    main:
        image: 'local-docker://af-design:latest'
        command: python3 root.py
        working_directory: /
        input_files: []
        output_files: []
        source_files: []
        gpu: required
main_output_file: /output.md
