biolib_version: 2
modules:
    main:
        image: 'local-docker://af-design:latest'
        command: python3 root.py
        working_directory: /
        input_files:
            - COPY / /
        output_files:
            - COPY /output/ /
        source_files:
            - COPY / /
        gpu: required
main_output_file: /output.md
